### ISSUE TITLE
maybe a dependency package version issue

### ISSUE THREAD

**Issue by CallMeEleven** [MesihK/prost#3]
Dear Mesih,

I get an RuntimeError .when i run : prost makedb XX.fasta sp.prdb , It will generate an error message like this：
`Traceback (most recent call last):
  File "/home/shiyi/miniconda3/envs/py3_10/bin/prost", line 417, in <module>
    cli()
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/shiyi/miniconda3/envs/py3_10/bin/prost", line 270, in makedb
    from pyprost import quantSeq
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/pyprost/__init__.py", line 58, in <module>
    from .prosttools import quantSeq,prostDistance
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/pyprost/prosttools.py", line 1, in <module>
    from .esmts25_13 import embed
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/pyprost/esmts25_13.py", line 16, in <module>
    esm1b = torch.jit.load(prostdir+'/traced_esm1b_25_13.pt').eval()
  File "/home/shiyi/miniconda3/envs/py3_10/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

it seems to be a problem with the click package ， I tried all distributions of click package，but it does not work.
What is the click package version that is compatible with PROST v0.2.15? 

Or please take a look, maybe there are other problems?

Thank you so much！

**Comment by MesihK** [comment]
Hi CallMeEleven,

This error seems to be caused by the corrupted `traced_esm1b_25_13.pt` file. You can delete `~/.config/prost/` directory and try running PROST again. (If you are using the `$PROSTDIR` environment variable, please delete that folder.) 

Thanks for trying PROST!
Best,
Mesih

**Comment by CallMeEleven** [comment]
I tried to upgrade to v0.2.15 and delete 'traced_esm1b_25_13' in '~/.config/prost/ ' .ptand run ' prost.py makedb XX.fasta sp.prdb'again. PROST would download 'traced_esm1b_25_13'  again and the same error occurred.
' prost.py makedb UP000000768_4558.fasta  db1.prdb
Traceback (most recent call last):
  File "/home/shiyi/miniconda3/envs/prost2.15/bin/prost.py", line 574, in <module>
    cli()
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/shiyi/miniconda3/envs/prost2.15/bin/prost.py", line 274, in makedb
    from pyprost import quantSeq
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/pyprost/__init__.py", line 58, in <module>
    from .prosttools import quantSeq,prostDistance
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/pyprost/prosttools.py", line 1, in <module>
    from .esmts25_13 import embed
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/pyprost/esmts25_13.py", line 16, in <module>
    esm1b = torch.jit.load(prostdir+'/traced_esm1b_25_13.pt').eval()
  File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory'

Can commenting out the line of code downloaded in the prost.py file solve the problem?

**Comment by CallMeEleven** [comment]
I tried to upgrade to v0.2.15 and delete` 'traced_esm1b_25_13' in '~/.config/prost/ ' `.ptand run `'prost.py makedb XX.fasta sp.prdb'`again. PROST would download 'traced_esm1b_25_13' again and the same error occurred.
```
'prost.py makedb UP000000768_4558.fasta db1.prdb
Traceback (most recent call last):
File "/home/shiyi/miniconda3/envs/prost2.15/bin/prost.py", line 574, in
cli()
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/home/shiyi/miniconda3/envs/prost2.15/bin/prost.py", line 274, in makedb
from pyprost import quantSeq
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/pyprost/init.py", line 58, in
from .prosttools import quantSeq,prostDistance
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/pyprost/prosttools.py", line 1, in
from .esmts25_13 import embed
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/pyprost/esmts25_13.py", line 16, in
esm1b = torch.jit.load(prostdir+'/traced_esm1b_25_13.pt').eval()
File "/home/shiyi/miniconda3/envs/prost2.15/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes) # type: ignore[call-arg]
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory'
```

Can commenting out the line of code downloaded in the 'prost.py' file solve the problem?

**Comment by CallMeEleven** [comment]
Hi Mesih,
I tried manually downloading the five required files, putting them into the specified folder and running the program again, and the program finally ran normally. 
Thank you for your valuable answer.
I would like to suggest the possibility of optimizing the program script and making appropriate parameter adjustments for different versions in the` __init__.py `file, if you may find it beneficial.

**Comment by MesihK** [comment]
Thanks for the update! It's great that you were able to solve the issue!
